In [0]:
from google.colab import drive

drive.mount('/content/gdrive', force_remount=True)
root_path = 'gdrive/My Drive/classification/'

Mounted at /content/gdrive


In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics 
from sklearn.metrics import classification_report

In [0]:
#mengimport dataset
fifa = pd.read_csv("gdrive/My Drive/classification/kmeansclustering.csv")
#manampilkan semua kolom
pd.set_option("display.max.columns", None)
#maksimal 2 angka dibelakang koma
pd.set_option("display.precision", 2)
#menampilkan sebagian data
fifa.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     190871  https://sofifa.com/player/190871/neymar-da-sil...   
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4     183277  https://sofifa.com/player/183277/eden-hazard/2...   

          short_name                            long_name  age  potential  \
0           L. Messi       Lionel Andrés Messi Cuccittini   32         94   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34         93   
2          Neymar Jr        Neymar da Silva Santos Junior   27         92   
3           J. Oblak                            Jan Oblak   26         93   
4          E. Hazard                          Eden Hazard   28         91   

   value_eur  wage_eur player_positions preferred_foot  \
0   95500000    565000       RW, CF, ST           Left   
1   58500000    405000           ST, LW          Right   
2  105500000    290000          LW, CAM          Right   
3   77500000    125000               GK          Right   
4   90000000    470000           LW, CF          Right   

   international_reputation  weak_foot  skill_moves      work_rate  \
0                         5          4            4     Medium/Low   
1                         5          4            5       High/Low   
2                         5          5            5    High/Medium   
3                         3          3            1  Medium/Medium   
4                         4          4            4    High/Medium   

    body_type real_face  release_clause_eur  \
0       Messi       Yes            1.96e+08   
1  C. Ronaldo       Yes            9.65e+07   
2      Neymar       Yes            1.95e+08   
3      Normal       Yes            1.65e+08   
4      Normal       Yes            1.84e+08   

                                         player_tags team_position  \
0  #Dribbler, #Distance Shooter, #Crosser, #FK Sp...            RW   
1  #Speedster, #Dribbler, #Distance Shooter, #Acr...            LW   
2  #Speedster, #Dribbler, #Playmaker  , #Crosser,...           CAM   
3                    #Speedster, #Dribbler, #Acrobat            GK   
4                    #Speedster, #Dribbler, #Acrobat            LW   

   team_jersey_number   loaned_from      joined  contract_valid_until  \
0                10.0  FC Barcelona  2004-07-01                2021.0   
1                 7.0  FC Barcelona  2018-07-10                2022.0   
2                10.0  FC Barcelona  2017-08-03                2022.0   
3                13.0  FC Barcelona  2014-07-16                2023.0   
4                 7.0  FC Barcelona  2019-07-01                2024.0   

  nation_position  nation_jersey_number  pace  shooting  passing  dribbling  \
0              LS                 12.11  87.0      92.0    92.00      96.00   
1              LS                  7.00  90.0      93.0    82.00      89.00   
2              LW                 10.00  91.0      85.0    87.00      95.00   
3              GK                  1.00  67.7      52.3    57.23      62.53   
4              LF                 10.00  91.0      83.0    86.00      94.00   

   defending  physic  gk_diving  gk_handling  gk_kicking  gk_reflexes  \
0      39.00   66.00      65.42        63.15       61.83        66.39   
1      35.00   78.00      65.42        63.15       61.83        66.39   
2      32.00   58.00      65.42        63.15       61.83        66.39   
3      51.55   64.88      87.00        92.00       78.00        89.00   
4      35.00   66.00      65.42        63.15       61.83        66.39   

   gk_speed  gk_positioning  \
0      37.8           63.37   
1      37.8           63.37   
2      37.8           63.37   
3      52.0           90.00   
4      37.8           63.37   

                                       player_traits  attacking_crossing  \
0  Beat Offside Trap, Argues with Officials, Ea

In [0]:
#mengecek missing values pada dataset
fifa.isna()

sofifa_id  player_url  short_name  long_name    age  potential  \
0          False       False       False      False  False      False   
1          False       False       False      False  False      False   
2          False       False       False      False  False      False   
3          False       False       False      False  False      False   
4          False       False       False      False  False      False   
...          ...         ...         ...        ...    ...        ...   
18273      False       False       False      False  False      False   
18274      False       False       False      False  False      False   
18275      False       False       False      False  False      False   
18276      False       False       False      False  False      False   
18277      False       False       False      False  False      False   

       value_eur  wage_eur  player_positions  preferred_foot  \
0          False     False             False           False   
1          False     False             False           False   
2          False     False             False           False   
3          False     False             False           False   
4          False     False             False           False   
...          ...       ...               ...             ...   
18273      False     False             False           False   
18274      False     False             False           False   
18275      False     False             False           False   
18276      False     False             False           False   
18277      False     False             False           False   

       international_reputation  weak_foot  skill_moves  work_rate  body_type  \
0                         False      False        False      False      False   
1                         False      False        False      False      False   
2                         False      False        False      False      False   
3                         False      False        False      False      False   
4                         False      False        False      False      False   
...                         ...        ...          ...        ...        ...   
18273                     False      False        False      False      False   
18274                     False      False        False      False      False   
18275                     False      False        False      False      False   
18276                     False      False        False      False      False   
18277                     False      False        False      False      False   

       real_face  release_clause_eur  player_tags  team_position  \
0          False               False        False          False   
1          False               False        False          False   
2          False               False        False          False   
3          False               False        False          False   
4          False               False        False          False   
...          ...                 ...          ...            ...   
18273      False               False        False          False   
18274      False               False        False          False   
18275      False               False        False          False   
18276      False               False        False          False   
18277      False               False        False          False   

       team_jersey_number  loaned_from  joined  contract_valid_until  \
0                   False        False   False                 False   
1                   False        False   False                 False   
2                   False        False   False                 False   
3                   False        False   False                 False   
4                   False        False   False                 False   
...                   ...          ...     ...                   ...   
18273               False        False   False                 Fals

In [0]:
#mendrop atribut antara potential hingga cluster secara permanen
fifa.drop(fifa.iloc[:, 6:98], inplace=True, axis = 1) 
fifa

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2         190871  https://sofifa.com/player/190871/neymar-da-sil...   
3         200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4         183277  https://sofifa.com/player/183277/eden-hazard/2...   
...          ...                                                ...   
18273     245006  https://sofifa.com/player/245006/shuai-shao/20...   
18274     250995  https://sofifa.com/player/250995/mingjie-xiao/...   
18275     252332  https://sofifa.com/player/252332/wei-zhang/20/...   
18276     251110  https://sofifa.com/player/251110/haijian-wang/...   
18277     233449  https://sofifa.com/player/233449/ximing-pan/20...   

              short_name                            long_name  age  potential  \
0               L. Messi       Lionel Andrés Messi Cuccittini   32         94   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34         93   
2              Neymar Jr        Neymar da Silva Santos Junior   27         92   
3               J. Oblak                            Jan Oblak   26         93   
4              E. Hazard                          Eden Hazard   28         91   
...                  ...                                  ...  ...        ...   
18273         Shao Shuai                                   邵帅   22         56   
18274       Xiao Mingjie                         Mingjie Xiao   22         56   
18275          Zhang Wei                                   张威   19         56   
18276       Wang Haijian                                  汪海健   18         54   
18277         Pan Ximing                                  潘喜明   26         51   

       cluster  
0            2  
1            2  
2            2  
3            4  
4            2  
...        ...  
18273        3  
18274        3  
18275        3  
18276        3  
18277        1  

[18278 rows x 7 columns]

In [0]:
#mendrop semua atribut kecuali age, potential, cluster
fifa.drop(fifa.iloc[:, 0:4], inplace=True, axis = 1) 
fifa

age  potential  cluster
0       32         94        2
1       34         93        2
2       27         92        2
3       26         93        4
4       28         91        2
...    ...        ...      ...
18273   22         56        3
18274   22         56        3
18275   19         56        3
18276   18         54        3
18277   26         51        1

[18278 rows x 3 columns]

In [0]:
#memasukkan nilai kelas cluster kedalam variable
fifa_df = fifa['cluster']
fifa_df

0        2
1        2
2        2
3        4
4        2
        ..
18273    3
18274    3
18275    3
18276    3
18277    1
Name: cluster, Length: 18278, dtype: int64

In [0]:
#memasukkan atribut kecuali kelas kedalam variable
fifa_la = fifa.drop(['cluster'], axis=1) 
fifa_la

age  potential
0       32         94
1       34         93
2       27         92
3       26         93
4       28         91
...    ...        ...
18273   22         56
18274   22         56
18275   19         56
18276   18         54
18277   26         51

[18278 rows x 2 columns]

In [0]:
#mensplit data jadi data train dan data set
x_train, x_test, y_train, y_test = train_test_split(fifa_la, fifa_df, test_size = 0.2, random_state = 0)

In [0]:
#melihat isi data test
x_test

age  potential
10114   23         74
13805   30         62
14836   21         72
8164    25         70
6608    30         69
...    ...        ...
13056   33         63
759     23         86
3374    23         79
5155    26         72
9783    29         66

[3656 rows x 2 columns]

In [0]:
#melihat isi data train
x_train

age  potential
6942    24         73
15728   24         64
6591    26         69
12889   34         63
7272    32         68
...    ...        ...
9225    25         70
13123   19         81
9845    26         66
10799   28         65
2732    24         80

[14622 rows x 2 columns]

In [0]:
#memasukkan fungsi naive bayes dan memprediksi x_test
NB = GaussianNB() 
nbtrain = NB.fit(x_train, y_train)
y_pred = nbtrain.predict(x_test)
y_pred

array([4, 1, 3, ..., 4, 2, 1])

In [0]:
#melihat hasil asli y_test
np.array(y_test)

array([4, 1, 3, ..., 4, 2, 1])

In [0]:
#membuat probabilitas dari hasil x_test
nbtrain.predict_proba(x_test)

array([[3.79535108e-03, 9.81543898e-02, 3.49954864e-01, 5.48095395e-01],
       [9.88961429e-01, 4.76653353e-03, 6.27198818e-03, 4.94454972e-08],
       [8.86240286e-04, 6.84279584e-03, 5.36061708e-01, 4.56209256e-01],
       ...,
       [1.40966023e-04, 7.65219950e-02, 1.03113528e-02, 9.13025686e-01],
       [1.01899086e-01, 5.34867157e-01, 3.41523833e-01, 2.17099235e-02],
       [8.98572696e-01, 5.92101505e-02, 4.22111325e-02, 6.02087934e-06]])

In [0]:
#mencari ketepatan prediksi dengan confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 883,    0,    0,    0],
       [  34,  687,    9,    0],
       [  13,    0, 1136,    0],
       [   0,    4,    6,  884]])

In [0]:
#mengeluarkan hasil akurasi
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9819474835886215


In [0]:
#menampilkan hasil klasifikasi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.95      1.00      0.97       883
           2       0.99      0.94      0.97       730
           3       0.99      0.99      0.99      1149
           4       1.00      0.99      0.99       894

    accuracy                           0.98      3656
   macro avg       0.98      0.98      0.98      3656
weighted avg       0.98      0.98      0.98      3656

