In [0]:
from google.colab import drive

drive.mount('/content/gdrive', force_remount=True)
root_path = 'gdrive/My Drive/classification/'

Mounted at /content/gdrive


In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics 
from sklearn.metrics import classification_report

In [0]:
#mengimport dataset
fifa = pd.read_csv("gdrive/My Drive/classification/kmeansclusteringver2.csv")
#manampilkan semua kolom
pd.set_option("display.max.columns", None)
#maksimal 2 angka dibelakang koma
pd.set_option("display.precision", 2)
#menampilkan sebagian data
fifa.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     190871  https://sofifa.com/player/190871/neymar-da-sil...   
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4     183277  https://sofifa.com/player/183277/eden-hazard/2...   

          short_name                            long_name  age  overall  \
0           L. Messi       Lionel Andrés Messi Cuccittini   32       94   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34       93   
2          Neymar Jr        Neymar da Silva Santos Junior   27       92   
3           J. Oblak                            Jan Oblak   26       91   
4          E. Hazard                          Eden Hazard   28       91   

   potential  value_eur  wage_eur player_positions preferred_foot  \
0         94   95500000    565000       RW, CF, ST           Left   
1         93   58500000    405000           ST, LW          Right   
2         92  105500000    290000          LW, CAM          Right   
3         93   77500000    125000               GK          Right   
4         91   90000000    470000           LW, CF          Right   

   international_reputation  weak_foot  skill_moves      work_rate  \
0                         5          4            4     Medium/Low   
1                         5          4            5       High/Low   
2                         5          5            5    High/Medium   
3                         3          3            1  Medium/Medium   
4                         4          4            4    High/Medium   

    body_type real_face  release_clause_eur  \
0       Messi       Yes            1.96e+08   
1  C. Ronaldo       Yes            9.65e+07   
2      Neymar       Yes            1.95e+08   
3      Normal       Yes            1.65e+08   
4      Normal       Yes            1.84e+08   

                                         player_tags team_position  \
0  #Dribbler, #Distance Shooter, #Crosser, #FK Sp...            RW   
1  #Speedster, #Dribbler, #Distance Shooter, #Acr...            LW   
2  #Speedster, #Dribbler, #Playmaker  , #Crosser,...           CAM   
3                    #Speedster, #Dribbler, #Acrobat            GK   
4                    #Speedster, #Dribbler, #Acrobat            LW   

   team_jersey_number   loaned_from      joined  contract_valid_until  \
0                10.0  FC Barcelona  2004-07-01                2021.0   
1                 7.0  FC Barcelona  2018-07-10                2022.0   
2                10.0  FC Barcelona  2017-08-03                2022.0   
3                13.0  FC Barcelona  2014-07-16                2023.0   
4                 7.0  FC Barcelona  2019-07-01                2024.0   

  nation_position  nation_jersey_number  pace  shooting  passing  dribbling  \
0              LS                 12.11  87.0      92.0    92.00      96.00   
1              LS                  7.00  90.0      93.0    82.00      89.00   
2              LW                 10.00  91.0      85.0    87.00      95.00   
3              GK                  1.00  67.7      52.3    57.23      62.53   
4              LF                 10.00  91.0      83.0    86.00      94.00   

   defending  physic  gk_diving  gk_handling  gk_kicking  gk_reflexes  \
0      39.00   66.00      65.42        63.15       61.83        66.39   
1      35.00   78.00      65.42        63.15       61.83        66.39   
2      32.00   58.00      65.42        63.15       61.83        66.39   
3      51.55   64.88      87.00        92.00       78.00        89.00   
4      35.00   66.00      65.42        63.15       61.83        66.39   

   gk_speed  gk_positioning  \
0      37.8           63.37   
1      37.8           63.37   
2      37.8           63.37   
3      52.0           90.00   
4      37.8           63.37   

                                       player_traits  attacking_cross

In [0]:
f#mengecek missing values pada dataset
fifa.isna()

sofifa_id  player_url  short_name  long_name    age  overall  \
0          False       False       False      False  False    False   
1          False       False       False      False  False    False   
2          False       False       False      False  False    False   
3          False       False       False      False  False    False   
4          False       False       False      False  False    False   
...          ...         ...         ...        ...    ...      ...   
18273      False       False       False      False  False    False   
18274      False       False       False      False  False    False   
18275      False       False       False      False  False    False   
18276      False       False       False      False  False    False   
18277      False       False       False      False  False    False   

       potential  value_eur  wage_eur  player_positions  preferred_foot  \
0          False      False     False             False           False   
1          False      False     False             False           False   
2          False      False     False             False           False   
3          False      False     False             False           False   
4          False      False     False             False           False   
...          ...        ...       ...               ...             ...   
18273      False      False     False             False           False   
18274      False      False     False             False           False   
18275      False      False     False             False           False   
18276      False      False     False             False           False   
18277      False      False     False             False           False   

       international_reputation  weak_foot  skill_moves  work_rate  body_type  \
0                         False      False        False      False      False   
1                         False      False        False      False      False   
2                         False      False        False      False      False   
3                         False      False        False      False      False   
4                         False      False        False      False      False   
...                         ...        ...          ...        ...        ...   
18273                     False      False        False      False      False   
18274                     False      False        False      False      False   
18275                     False      False        False      False      False   
18276                     False      False        False      False      False   
18277                     False      False        False      False      False   

       real_face  release_clause_eur  player_tags  team_position  \
0          False               False        False          False   
1          False               False        False          False   
2          False               False        False          False   
3          False               False        False          False   
4          False               False        False          False   
...          ...                 ...          ...            ...   
18273      False               False        False          False   
18274      False               False        False          False   
18275      False               False        False          False   
18276      False               False        False          False   
18277      False               False        False          False   

       team_jersey_number  loaned_from  joined  contract_valid_until  \
0                   False        False   False                 False   
1                   False        False   False                 False   
2                   False        False   False                 False   
3                   False        False   False                 False   
4                   False        False   False                 False   
...                   ...      

In [0]:
#mendrop atribut antara overall hingga cluster secara permanen
fifa.drop(fifa.iloc[:, 6:99], inplace=True, axis = 1) 
fifa

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2         190871  https://sofifa.com/player/190871/neymar-da-sil...   
3         200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4         183277  https://sofifa.com/player/183277/eden-hazard/2...   
...          ...                                                ...   
18273     245006  https://sofifa.com/player/245006/shuai-shao/20...   
18274     250995  https://sofifa.com/player/250995/mingjie-xiao/...   
18275     252332  https://sofifa.com/player/252332/wei-zhang/20/...   
18276     251110  https://sofifa.com/player/251110/haijian-wang/...   
18277     233449  https://sofifa.com/player/233449/ximing-pan/20...   

              short_name                            long_name  age  overall  \
0               L. Messi       Lionel Andrés Messi Cuccittini   32       94   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34       93   
2              Neymar Jr        Neymar da Silva Santos Junior   27       92   
3               J. Oblak                            Jan Oblak   26       91   
4              E. Hazard                          Eden Hazard   28       91   
...                  ...                                  ...  ...      ...   
18273         Shao Shuai                                   邵帅   22       48   
18274       Xiao Mingjie                         Mingjie Xiao   22       48   
18275          Zhang Wei                                   张威   19       48   
18276       Wang Haijian                                  汪海健   18       48   
18277         Pan Ximing                                  潘喜明   26       48   

       cluster  
0            3  
1            3  
2            2  
3            2  
4            2  
...        ...  
18273        4  
18274        4  
18275        4  
18276        4  
18277        4  

[18278 rows x 7 columns]

In [0]:
#mendrop semua atribut kecuali age, overall, cluster
fifa.drop(fifa.iloc[:, 0:4], inplace=True, axis = 1) 
fifa

age  overall  cluster
0       32       94        3
1       34       93        3
2       27       92        2
3       26       91        2
4       28       91        2
...    ...      ...      ...
18273   22       48        4
18274   22       48        4
18275   19       48        4
18276   18       48        4
18277   26       48        4

[18278 rows x 3 columns]

In [0]:
#memasukkan nilai kelas cluster kedalam variable
fifa_df = fifa['cluster']
fifa_df

0        3
1        3
2        2
3        2
4        2
        ..
18273    4
18274    4
18275    4
18276    4
18277    4
Name: cluster, Length: 18278, dtype: int64

In [0]:
#memasukkan atribut kecuali kelas kedalam variable
fifa_la = fifa.drop(['cluster'], axis=1) 
fifa_la

age  overall
0       32       94
1       34       93
2       27       92
3       26       91
4       28       91
...    ...      ...
18273   22       48
18274   22       48
18275   19       48
18276   18       48
18277   26       48

[18278 rows x 2 columns]

In [0]:
#mensplit data jadi data train dan data set
x_train, x_test, y_train, y_test = train_test_split(fifa_la, fifa_df, test_size = 0.2, random_state = 0)

In [0]:
#melihat isi dari data test
x_test

age  overall
10114   23       65
13805   30       62
14836   21       60
8164    25       67
6608    30       69
...    ...      ...
13056   33       63
759     23       78
3374    23       72
5155    26       70
9783    29       66

[3656 rows x 2 columns]

In [0]:
#melihat isi dari data train
x_train

age  overall
6942    24       68
15728   24       59
6591    26       69
12889   34       63
7272    32       68
...    ...      ...
9225    25       66
13123   19       62
9845    26       66
10799   28       65
2732    24       73

[14622 rows x 2 columns]

In [0]:
#memasukkan fungsi naive bayes dan memprediksi x_test
NB = GaussianNB() 
nbtrain = NB.fit(x_train, y_train)
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 4, ..., 2, 2, 1])

In [0]:
#melihat hasil asli y_test
np.array(y_test)

array([1, 1, 4, ..., 2, 2, 1])

In [0]:
#membuat probabilitas dari hasil x_test
nbtrain.predict_proba(x_test)

array([[5.66518050e-01, 1.34045418e-01, 3.33174838e-04, 2.99103357e-01],
       [5.34128890e-01, 5.14935782e-03, 4.60720955e-01, 7.97348422e-07],
       [9.94078508e-03, 1.56889965e-03, 1.02110746e-06, 9.88489294e-01],
       ...,
       [3.84819175e-02, 9.45027025e-01, 5.54468276e-04, 1.59365889e-02],
       [4.37511834e-01, 5.32443664e-01, 2.94535182e-02, 5.90983909e-04],
       [6.74969750e-01, 3.77214912e-02, 2.87306051e-01, 2.70746457e-06]])

In [0]:
#mencari ketepatan prediksi dengan confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 910,    0,   29,    1],
       [  16,  703,   15,   31],
       [  17,    0,  784,    0],
       [  16,    0,    0, 1134]])

In [0]:
#mengeluaran hasil akhurasi
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9658096280087527


In [0]:
#menampilkan hasil klasifikasi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.95      0.97      0.96       940
           2       1.00      0.92      0.96       765
           3       0.95      0.98      0.96       801
           4       0.97      0.99      0.98      1150

    accuracy                           0.97      3656
   macro avg       0.97      0.96      0.96      3656
weighted avg       0.97      0.97      0.97      3656

